library(openxlsx)
DATA <- read.xlsx("MOVIE.xlsx")
Subs<-subset(DATA,(!is.na(DATA[,24])))
Subs <- subset(Subs,(!is.na(Subs[,26])))
Subs[,24] <- sapply(Subs[,24],as.numeric)
Subs[,26] <- sapply(Subs[ ,26],as.numeric)
Subs1 <- subset(Subs,(Subs[,24]<=2015))
populationMean <- mean(Subs1[,26])
populationVariance <- var(Subs1[,26])
print(c("Population mean of all movies upto 2015 = ",populationMean))
Subs2 <- subset(Subs,(Subs[,24]==2016))
sampleMean <- mean(Subs2[,26])
sampleVariance <- var(Subs2[,26])
n <- nrow(Subs2)
zknown <- (sampleMean-populationMean)/(populationVariance/sqrt(n))
alpha <- 0.05
z.alpha <- qnorm(1-alpha)
print(c("Z at alpha = 0.05 ",-z.alpha))
print(c("Z known variance = ",zknown))
zunknown <- (sampleMean-populationMean)/(sampleVariance/sqrt(n))
print(c("Z unknown variance = ",zunknown))
#Hence we accept the hypothesis that popularity of films increases with year since z known and z unknown are greater than z alpha
