library("graphics")
library("openxlsx")
library("psych")
df <- read.xlsx("IRIS.xlsx")
popMean1 <- mean(df[[2]])
popMean2 <- mean(df[[3]])
popMean3 <- mean(df[[4]])
popMean4 <- mean(df[[5]])
mysample <- df[sample(nrow(df), 50,
  	replace=FALSE),]
samMean1 <- mean(mysample[[2]])
samMean2 <- mean(mysample[[3]])
samMean3 <- mean(mysample[[4]])
samMean4 <- mean(mysample[[5]])
print(c("Sepal length mean:",popMean1))
print(c("Sepal width mean:",popMean2))
print(c("Petal length mean:",popMean3))
print(c("Petal width mean:",popMean4))
s1 = var(mysample[[2]])
s2 = var(mysample[[3]])
s3 = var(mysample[[4]])
s4 = var(mysample[[5]])
var1= mean((mysample[[2]]-mean(mysample[[2]]))^2)
var2= mean((mysample[[3]]-mean(mysample[[3]]))^2)
var3= mean((mysample[[4]]-mean(mysample[[4]]))^2)
var4= mean((mysample[[5]]-mean(mysample[[5]]))^2)
o1 <- c("Sepal length","Sample variance:",s1,"Population variance:",var1)
o2 <- c("Sepal width","Sample variance:",s2,"Population variance:",var2)
o3 <- c("Petal length","Sample variance:",s3,"Population variance:",var3)
o4 <- c("Petal width","Sample variance:",s4,"Population variance:",var4)
print(o1)
print(o2)
print(o3)
print(o4)
